SRC_CALLSIGN = 'W2GMD-14'
DST_CALLSIGN = 'PYKISS'

FEND = 0xC0

ACKNOWLEDGE = 0xBB
ERROR       = 0x32

TELECOM_UPLOAD_GUIDANCE	 = 0xC9
TELECOM_GET_HEALTH       = 0x4C
TELECOM_OVERRIDE_ANTENNA = 0x6A
TELECOM_DEBUG_ON         = 0xF0
TELECOM_DEBUG_OFF        = 0x0F
TELECOM_DEBUG_TOGGLE     = 0xAA

SOF = 0x02
EOF = 0x03
